import { ParticipantView, ConnectionQuality, LiveKitRoom, MediaControlButton, TrackSource, Participants } from '@livekit/auth-helpers-nextjs';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const params = typeof window !== 'undefined' ? new URLSearchParams(location.search) : null;

  const roomName = params?.get('room') ?? 'test-room';
  const userIdentity = params?.get('user') ?? 'test-user';
  // const roomState = useRoom();
  const [connect, setConnected] = useState(false);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>LiveKit Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://livekit.io">LiveKit</a> 
        </h1>
        {/* <p>Status: {roomState.connectionState} <br/> Nr. of participants: {roomState.participants.length} </p> */}
        <button onClick={() => setConnected(!connect)}>{connect ? 'Disconnect' : 'Connect'}</button>
        <MediaControlButton type={TrackSource.Camera}></MediaControlButton>
        <MediaControlButton type={TrackSource.Microphone}></MediaControlButton>
        <MediaControlButton type={TrackSource.ScreenShare}></MediaControlButton>
        <LiveKitRoom roomName={roomName} userIdentity={userIdentity} connect={connect}>
          <Participants>
            <ParticipantView >
              <ConnectionQuality/>
            </ParticipantView>
          </Participants>
        </LiveKitRoom>
        
      </main>
      
    </div>
  );
};

export default Home;
