import type { NextPage } from 'next';
import Head from 'next/head';
import { EXAMPLE_ROUTES } from '../lib/routes';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>LiveKit Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>JS Component Examples:</h1>
        <ul>
          {Object.entries(EXAMPLE_ROUTES).map(([name, href], index) => {
            return (
              <li key={index}>
                <a href={href}>{name}</a>
              </li>
            );
          })}
        </ul>
      </main>
    </div>
  );
};

export default Home;
