// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
// See LICENSE in the project root for license information.

import { IDocNodeParameters, DocNode } from '@microsoft/tsdoc';
import { CustomDocNodeKind } from './CustomDocNodeKind';

/**
 * Constructor parameters for {@link DocMdComment}.
 */
export interface IDocMdCommentParameters extends IDocNodeParameters {
  text: string;
}

/**
 * Add a Markdown comment.
 *
 * @example
 * ```<!-- Do not edit this file. It is automatically generated by API Documenter. -->\n\n
 * ```
 */
export class DocMdComment extends DocNode {
  public readonly text: string;

  public constructor(parameters: IDocMdCommentParameters) {
    super(parameters);
    this.text = parameters.text;
  }

  /** @override */
  public get kind(): string {
    return CustomDocNodeKind.MdComment;
  }
}
