import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  cloneAndCreateBranch,
  commitPushAndOpenPr,
  formatChanges,
  ghAuthPreflight,
  hasDiff,
  installDependencies,
  onInterrupt,
  removeTempDir,
  run,
  runCapture,
} from './lib/publish-utils.ts';

type PublishOptions = {
  registryAlreadyBuilt?: boolean;
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SHADCN_PKG_DIR = path.join(__dirname, '..');
const ENV_LOCAL_PATH = path.join(SHADCN_PKG_DIR, '.env.local');
const REPO = 'livekit/web';
const BASE_BRANCH = 'main';
const BRANCH_PREFIX = 'chore/update-agents-ui-registry';
const COMMIT_MESSAGE = 'chore(agents-ui): update registry + prop-types from @livekit/agents-ui';
const PR_TITLE = 'chore(agents-ui): update registry + prop-types';

function writeTempEnvLocal(tmpDir: string): void {
  console.log('--------------------------------');
  console.log('Pointing .env.local at the tmp livekit/web checkout');
  const destRegistryPath = path.join(tmpDir, 'apps/www/agents-ui-registry');
  const destPropTypesPath = path.join(tmpDir, 'apps/docs/lib/shadcn/prop-types.json');
  fs.writeFileSync(
    ENV_LOCAL_PATH,
    `DEST_REGISTRY_PATH=${destRegistryPath}\nDEST_PROP_TYPES_PATH=${destPropTypesPath}\n`,
  );
}

function deployRegistry(registryAlreadyBuilt: boolean): void {
  console.log('--------------------------------');
  if (registryAlreadyBuilt) {
    console.log('Deploying already-built registry');
    run(['node', '--experimental-strip-types', '--env-file=.env.local', './scripts/update.ts'], {
      cwd: SHADCN_PKG_DIR,
    });
  } else {
    console.log('Building and deploying registry');
    run(['pnpm', 'shadcn:deploy'], { cwd: SHADCN_PKG_DIR });
  }
}

function restoreEnvLocal(hadEnvLocal: boolean, envBackup: string | null): void {
  if (hadEnvLocal && envBackup !== null) {
    fs.writeFileSync(ENV_LOCAL_PATH, envBackup);
  } else {
    fs.rmSync(ENV_LOCAL_PATH, { force: true });
  }
}

function buildPrBody(sourceSha: string): string {
  return `Updates \`apps/www/agents-ui-registry\` and \`apps/docs/lib/shadcn/prop-types.json\` from the latest build of [livekit/components-js](https://github.com/livekit/components-js) at ${sourceSha}.\n\nGenerated by \`packages/shadcn/scripts/publish-livekit-web.ts\`.`;
}

export async function publishLivekitWeb(options: PublishOptions = {}): Promise<{
  success: boolean;
  skipped?: boolean;
  prUrl?: string;
}> {
  ghAuthPreflight();

  let tmpDir: string | undefined;
  const hadEnvLocal = fs.existsSync(ENV_LOCAL_PATH);
  const envBackup = hadEnvLocal ? fs.readFileSync(ENV_LOCAL_PATH, 'utf-8') : null;
  const cleanup = () => {
    restoreEnvLocal(hadEnvLocal, envBackup);
    removeTempDir(tmpDir);
  };
  const unregisterInterruptHandler = onInterrupt(cleanup);

  try {
    const cloned = cloneAndCreateBranch(REPO, 'livekit-web-', BRANCH_PREFIX, BASE_BRANCH);
    tmpDir = cloned.tmpDir;

    writeTempEnvLocal(tmpDir);
    deployRegistry(options.registryAlreadyBuilt ?? false);
    installDependencies(tmpDir);
    formatChanges(tmpDir, ['pnpm', '--filter', 'www', '--filter', 'docs', 'format']);

    if (!hasDiff(tmpDir)) {
      console.log('No changes after sync — skipping PR');
      return { success: true, skipped: true };
    }

    const sourceSha = runCapture(['git', 'rev-parse', 'HEAD'], { cwd: SHADCN_PKG_DIR });
    const prUrl = await commitPushAndOpenPr({
      repo: REPO,
      cwd: tmpDir,
      branch: cloned.branch,
      base: BASE_BRANCH,
      title: PR_TITLE,
      body: buildPrBody(sourceSha),
      commitMessage: COMMIT_MESSAGE,
    });

    if (!prUrl) {
      return { success: true, skipped: true };
    }
    return { success: true, prUrl };
  } finally {
    unregisterInterruptHandler();
    cleanup();
  }
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  publishLivekitWeb()
    .then((result) => {
      console.log('Done', result);
    })
    .catch((err) => {
      console.error(err);
      process.exitCode = 1;
    });
}
