import { spawn, type ChildProcess } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  cloneAndCreateBranch,
  commitPushAndOpenPr,
  ghAuthPreflight,
  hasDiff,
  isPortInUse,
  killServer,
  removeTempDir,
  run,
  runCapture,
  waitForHttp,
} from './lib/publish-utils.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SHADCN_PKG_DIR = path.join(__dirname, '..');
const REPO = 'livekit-examples/agent-starter-react';
const PORT = 3210;
const REGISTRY_URL = `http://localhost:${PORT}/r/{name}.json`;
const BRANCH_PREFIX = 'chore/update-agents-ui-registry';
const COMMIT_MESSAGE = 'chore: sync agents-ui components from livekit/components-js';
const PR_TITLE = 'chore: sync agents-ui components';

function buildRegistry(): void {
  console.log('--------------------------------');
  console.log('Building registry');
  run(['pnpm', 'shadcn:build'], { cwd: SHADCN_PKG_DIR });
}

async function serveRegistry(): Promise<ChildProcess> {
  console.log('--------------------------------');
  console.log(`Serving registry on port ${PORT}`);
  const server = spawn('python3', ['-m', 'http.server', String(PORT), '-d', './dist'], {
    cwd: SHADCN_PKG_DIR,
    stdio: 'ignore',
  });
  await waitForHttp(`http://localhost:${PORT}/r/registry.json`);
  return server;
}

function pointComponentsJsonAtLocalRegistry(tmpDir: string): void {
  console.log('--------------------------------');
  console.log('Pointing components.json at the local registry');
  const componentsJsonPath = path.join(tmpDir, 'components.json');
  const componentsJson = JSON.parse(fs.readFileSync(componentsJsonPath, 'utf-8'));
  componentsJson.registries['@agents-ui'] = REGISTRY_URL;
  fs.writeFileSync(componentsJsonPath, JSON.stringify(componentsJson, null, 2) + '\n');
}

function installComponents(tmpDir: string): void {
  console.log('--------------------------------');
  console.log('Installing dependencies');
  run(['pnpm', 'install'], { cwd: tmpDir });

  console.log('--------------------------------');
  console.log('Running shadcn:install');
  run(['pnpm', 'shadcn:install'], { cwd: tmpDir });
}

function revertComponentsJson(tmpDir: string): void {
  console.log('--------------------------------');
  console.log('Reverting temporary components.json change');
  run(['git', 'checkout', '--', 'components.json'], { cwd: tmpDir });
}

function buildPrBody(sourceSha: string): string {
  return `Syncs \`@agents-ui\` components from the latest build of [livekit/components-js](https://github.com/livekit/components-js) at ${sourceSha}.\n\nGenerated by \`packages/shadcn/scripts/publish-agent-starter-react.ts\`.`;
}

export async function publishAgentStarterReact(): Promise<{
  success: boolean;
  skipped?: boolean;
  prUrl?: string;
}> {
  ghAuthPreflight();
  if (isPortInUse(PORT)) {
    throw new Error(
      `Port ${PORT} is already in use. Stop any running shadcn:serve process and try again.`,
    );
  }

  let server: ChildProcess | undefined;
  let tmpDir: string | undefined;

  try {
    buildRegistry();
    server = await serveRegistry();

    const cloned = cloneAndCreateBranch(REPO, 'agent-starter-react-', BRANCH_PREFIX);
    tmpDir = cloned.tmpDir;

    pointComponentsJsonAtLocalRegistry(tmpDir);
    installComponents(tmpDir);
    revertComponentsJson(tmpDir);

    if (!hasDiff(tmpDir)) {
      console.log('No changes after sync — skipping PR');
      return { success: true, skipped: true };
    }

    const sourceSha = runCapture(['git', 'rev-parse', 'HEAD'], { cwd: SHADCN_PKG_DIR });
    const prUrl = await commitPushAndOpenPr({
      repo: REPO,
      cwd: tmpDir,
      branch: cloned.branch,
      base: 'main',
      title: PR_TITLE,
      body: buildPrBody(sourceSha),
      commitMessage: COMMIT_MESSAGE,
    });

    if (!prUrl) {
      return { success: true, skipped: true };
    }
    return { success: true, prUrl };
  } finally {
    killServer(server);
    removeTempDir(tmpDir);
  }
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  publishAgentStarterReact()
    .then((result) => {
      console.log('Done', result);
    })
    .catch((err) => {
      console.error(err);
      process.exitCode = 1;
    });
}
