/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
/**
 * @internal
 */
const SvgCameraDisabledIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} fill="none" {...props}>
    <path
      stroke="#F5F5F5"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="m12.5 8.333 3.794-1.896a.833.833 0 0 1 1.206.745v5.636a.833.833 0 0 1-1.206.745L12.5 11.666zM10.833 5H4.167C3.247 5 2.5 5.746 2.5 6.667v6.666c0 .92.746 1.667 1.667 1.667h6.666c.92 0 1.667-.746 1.667-1.667V6.667c0-.92-.746-1.667-1.667-1.667"
    />
    <path
      stroke="#F84135"
      strokeLinecap="round"
      strokeWidth={1.667}
      d="m2.846 1.667 15.321 15.32"
    />
  </svg>
);
export default SvgCameraDisabledIcon;
