/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
/**
 * @internal
 */
const SvgLeaveIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width={26} height={20} fill="none" {...props}>
    <path
      stroke="#fff"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.688}
      d="m22.24 11.483-2.464 2.68-4.312-2.01.616-2.68a8.86 8.86 0 0 0-6.16 0l.616 2.68-4.312 2.01-2.464-2.68a1.98 1.98 0 0 1-.51-1.34c0-.502.184-.984.51-1.339C6.31 6.35 9.596 4.996 13 4.996s6.69 1.354 9.24 3.808c.326.355.51.837.51 1.34 0 .502-.184.984-.51 1.34"
    />
  </svg>
);
export default SvgLeaveIcon;
