/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
/**
 * @internal
 */
const SvgMicDisabledIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} fill="none" {...props}>
    <path
      stroke="#EAECEF"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="M12.496 4.167a2.5 2.5 0 0 0-5 0v4.167a2.5 2.5 0 1 0 5 0zM4.164 8.334a5.833 5.833 0 0 0 5.833 5.833m0 0a5.834 5.834 0 0 0 5.834-5.833m-5.834 5.833V17.5m-3.333 0h6.667"
    />
    <path
      stroke="#F84135"
      strokeLinecap="round"
      strokeWidth={1.667}
      d="m2.843 1.667 15.32 15.321"
    />
  </svg>
);
export default SvgMicDisabledIcon;
