/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
/**
 * @internal
 */
const SvgMicDisabledMiniIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width={16} height={16} fill="none" {...props}>
    <path
      stroke="#EAECEF"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.333}
      d="M9.997 3.334c0-1.105-.886-1.99-2-1.99a1.98 1.98 0 0 0-1.995 1.99v3.333c0 1.104.881 1.99 1.995 1.99s2-.886 2-1.99zM3.331 6.667A4.82 4.82 0 0 0 4.698 10c.875.909 2.07 1.334 3.3 1.334m0 0c1.23 0 2.425-.425 3.3-1.334a4.82 4.82 0 0 0 1.367-3.333m-4.667 4.667V14m-2.667 0h5.334"
    />
    <path stroke="#F84135" strokeLinecap="round" strokeWidth={1.333} d="M2.274 1.344 14.53 13.59" />
  </svg>
);
export default SvgMicDisabledMiniIcon;
