/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
/**
 * @internal
 */
const SvgSpeakingDotIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 21 20" {...props}>
    <circle cx={4.69} cy={10} r={1.667} fill="#82c1fc" data-follow-fill="#82c1fc" />
    <circle cx={10.524} cy={10} r={1.667} fill="#82c1fc" data-follow-fill="#82c1fc" />
    <circle cx={16.356} cy={10} r={1.667} fill="#82c1fc" data-follow-fill="#82c1fc" />
  </svg>
);
export default SvgSpeakingDotIcon;
