import { ComponentDoc } from 'react-docgen-typescript';

export const mdxTemplate = (def: ComponentDoc) => `---
title: ${splitCamelCase(def.displayName)}
subtitle: ${def.description.replaceAll('\n', ' ')} 
---

{/*
!!!! Autogenerated File !!!!
This file was created by @livekit/components-docs-gen and should not be changed manually.
The contents of this file can be replaced at any time which would lead to the loss of all manual changes.
*/}

import Usage from '@/components/js-components/Usage';
import PropsTable from '@/components/js-components/PropsTable';

## Usage

${def.tags?.example ? def.tags.example : 'No example yet.'}

<Usage of='${def.displayName}' />

## Props

<PropsTable data='${JSON.stringify(def.props, stringifyProps)}' />

`;

const splitCamelCase = (camelCaseStr: string) =>
  camelCaseStr.replace(/([a-z0-9])([A-Z])/g, '$1 $2');

const stringifyProps = (key: string, value: any) => {
  if (key === 'defaultValue') {
    // TODO: some `defaultValues` are in a non JSON compatible format and crash when trying to run JSON.parse on them.
    // At the moment we exclude them from the JSON string.
    return typeof value === 'object' ? null : value;
  }
  return value;
};
